name=MKE_I2C_Loadcell
version=1.0.0
author=MakerEdu.vn
maintainer=MakerEdu.vn
sentence=A library for interacting with the MKE-S18 I2C HX710 Loadcell Sensor module.
paragraph=Supports Tare, Calibration, Gram output, and EEPROM saving. Compatible with Uno, ESP32, and STM32.
category=Sensors
url=https://github.com/makereduvn/MKE-S18-HX711-I2C-LOADCELL-SENSOR
architectures=*
includes=MKE_I2C_Loadcell.h
