name=MKE_I2C_RFID
version=1.0.0
author=MakerEdu.vn
maintainer=MakerEdu.vn
sentence=Library for MKE I2C RFID RC522 module
paragraph=Provides an easy interface to control the MKE-M26-RC522-I2C-RFID-MODULE.
category=Communication
url=https://github.com/makereduvn/MKE-M26-RC522-I2C-RFID-MODULE
architectures=*
includes=MKE_I2C_RFID.h
